06:45:48.727 Running build in Washington, D.C., USA (East) – iad1
06:45:48.728 Build machine configuration: 2 cores, 8 GB
06:45:48.855 Cloning github.com/krimmmmm/mdl-cctv-floor-dashboard (Branch: main, Commit: c71454e)
06:45:49.189 Cloning completed: 334.000ms
06:45:50.133 Restored build cache from previous deployment (AEBjwAjE6ReMbSbszrPRj55UhEiq)
06:45:51.127 Running "vercel build"
06:45:51.145 Vercel CLI 54.7.1
06:45:51.697 Detected `pnpm-lock.yaml` version 9 generated by pnpm@10.x with package.json#packageManager pnpm@10.4.1+sha512.c753b6c3ad7afa13af388fa6d808035a008e30ea9993f58c6663e2bc5ff21679aa834db094987129aa4d488b86df57f7b634981b2f827cdcacc698cc0cfb88af
06:45:51.698 Running "install" command: `pnpm install --no-frozen-lockfile`...
06:45:53.939 Progress: resolved 0, reused 0, downloaded 1, added 0
06:45:54.961 Progress: resolved 58, reused 0, downloaded 57, added 0
06:45:55.941 Progress: resolved 79, reused 0, downloaded 78, added 0
06:45:56.943 Progress: resolved 223, reused 0, downloaded 207, added 0
06:45:57.941 Progress: resolved 237, reused 0, downloaded 221, added 0
06:45:58.958 Progress: resolved 302, reused 0, downloaded 280, added 0
06:45:59.946 Progress: resolved 460, reused 0, downloaded 356, added 0
06:46:00.946 Progress: resolved 592, reused 0, downloaded 481, added 0
06:46:01.944 Progress: resolved 794, reused 0, downloaded 662, added 0
06:46:02.038  WARN  2 deprecated subdependencies found: @esbuild-kit/core-utils@3.3.2, @esbuild-kit/esm-loader@2.6.5
06:46:02.136 Already up to date
06:46:02.183 Progress: resolved 794, reused 0, downloaded 662, added 0, done
06:46:02.532  WARN  Issues with peer dependencies found
06:46:02.533 .
06:46:02.533 ├─┬ @trpc/client 11.17.0
06:46:02.533 │ └── ✕ unmet peer typescript@>=5.7.2: found 5.6.3
06:46:02.533 ├─┬ @trpc/server 11.17.0
06:46:02.534 │ └── ✕ unmet peer typescript@>=5.7.2: found 5.6.3
06:46:02.534 ├─┬ @trpc/react-query 11.17.0
06:46:02.534 │ └── ✕ unmet peer typescript@>=5.7.2: found 5.6.3
06:46:02.534 └─┬ @builder.io/vite-plugin-jsx-loc 0.1.1
06:46:02.534   └── ✕ unmet peer vite@"^4.0.0 || ^5.0.0": found 7.1.9
06:46:02.535 
06:46:02.536 Done in 9.3s using pnpm v10.4.1
06:46:02.896 
06:46:02.897 > mdl_cctv_floor_dashboard@1.0.0 build
06:46:02.897 > vite build
06:46:02.897 
06:46:03.373 vite v7.1.9 building for production...
06:46:03.471 transforming...
06:46:05.916 Error processing file /vercel/path0/client/src/components/modals/FiberRouteStatusModal.tsx: SyntaxError: Unexpected token, expected "," (231:6)
06:46:05.917     at constructor (/vercel/path0/node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/lib/index.js:367:19)
06:46:05.917     at TypeScriptParserMixin.raise (/vercel/path0/node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/lib/index.js:6630:19)
06:46:05.917     at TypeScriptParserMixin.unexpected (/vercel/path0/node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/lib/index.js:6650:16)
06:46:05.918     at TypeScriptParserMixin.expect (/vercel/path0/node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/lib/index.js:6930:12)
06:46:05.919     at TypeScriptParserMixin.parseParenAndDistinguishExpression (/vercel/path0/node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/lib/index.js:11669:14)
06:46:05.919     at TypeScriptParserMixin.parseExprAtom (/vercel/path0/node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/lib/index.js:11335:23)
06:46:05.920     at TypeScriptParserMixin.parseExprAtom (/vercel/path0/node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/lib/index.js:4797:20)
06:46:05.920     at TypeScriptParserMixin.parseExprSubscripts (/vercel/path0/node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/lib/index.js:11085:23)
06:46:05.920     at TypeScriptParserMixin.parseUpdate (/vercel/path0/node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/lib/index.js:11070:21)
06:46:05.921     at TypeScriptParserMixin.parseMaybeUnary (/vercel/path0/node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/lib/index.js:11050:23) {
06:46:05.921   code: 'BABEL_PARSER_SYNTAX_ERROR',
06:46:05.921   reasonCode: 'UnexpectedToken',
06:46:05.922   loc: Position { line: 231, column: 6, index: 7354 },
06:46:05.922   pos: 7354,
06:46:05.922   syntaxPlugin: undefined
06:46:05.922 }
06:46:06.143 ✓ 1740 modules transformed.
06:46:06.144 ✗ Build failed in 2.74s
06:46:06.145 error during build:
06:46:06.145 [vite:esbuild] Transform failed with 1 error:
06:46:06.145 /vercel/path0/client/src/components/modals/FiberRouteStatusModal.tsx:231:6: ERROR: Expected ")" but found "{"
06:46:06.145 file: /vercel/path0/client/src/components/modals/FiberRouteStatusModal.tsx:231:6
06:46:06.145 
06:46:06.146 Expected ")" but found "{"
06:46:06.146 229 |        </div>
06:46:06.146 230 |      </div>
06:46:06.146 231 |        {previewImage && (
06:46:06.146     |        ^
06:46:06.146 232 |          <div
06:46:06.146 233 |            className="fixed inset-0 z-[999999] bg-black/95 flex items-center justify-center cursor-zoom-out"
06:46:06.147 
06:46:06.147     at failureErrorWithLog (/vercel/path0/node_modules/.pnpm/esbuild@0.25.10/node_modules/esbuild/lib/main.js:1467:15)
06:46:06.147     at /vercel/path0/node_modules/.pnpm/esbuild@0.25.10/node_modules/esbuild/lib/main.js:736:50
06:46:06.147     at responseCallbacks.<computed> (/vercel/path0/node_modules/.pnpm/esbuild@0.25.10/node_modules/esbuild/lib/main.js:603:9)
06:46:06.147     at handleIncomingPacket (/vercel/path0/node_modules/.pnpm/esbuild@0.25.10/node_modules/esbuild/lib/main.js:658:12)
06:46:06.147     at Socket.readFromStdout (/vercel/path0/node_modules/.pnpm/esbuild@0.25.10/node_modules/esbuild/lib/main.js:581:7)
06:46:06.147     at Socket.emit (node:events:509:28)
06:46:06.147     at addChunk (node:internal/streams/readable:563:12)
06:46:06.150     at readableAddChunkPushByteMode (node:internal/streams/readable:514:3)
06:46:06.150     at Readable.push (node:internal/streams/readable:394:5)
06:46:06.150     at Pipe.onStreamRead (node:internal/stream_base_commons:189:23)
06:46:06.202 Error: Command "npm run build" exited with 1
